{% set name = "cymysql" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61dd860cc04997912b433988112059057d0379ecf3264874c062f42cb796766e

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - cython
    - setuptools
  run:
    - python

test:
  imports:
    - cymysql
    - cymysql.constants

about:
  home: https://github.com/nakagami/CyMySQL/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python MySQL Driver using Cython
  dev_url: https://github.com/nakagami/CyMySQL/

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - mwilson8
    - benhuff
    - oblute
    - ndmaxar
