travis:
  secure:
    BINSTAR_TOKEN: MTKc66DaNx5vSrTEaAzAnqsxZl7g8JvQjYR2I5nKpRuWlG1ZhbuhuS4Bw4yBddmNp+pwEEPaUMsmt3B4oXslHTf43m9OsCEuCq8JZqtyJd7zAXbRID7mqxsSSOtWadbPj9K6G0V/qzzXKZQYPOMALUvJulD7hHLrgjqVEVzgWTC4YiEieunZg8GYgjonHgOUbY6Ht9VBwSkK7LD70SKcF5Halr0Y83SeHaCELvuDe3sAN4XsPIN8kjUgvcoHYVa5zKYaRSSmAuRSVOIq9n21EfJ/T9uuJGfXNM+xIeEeVb0pUoSQbUieDi/F3v3JA1w5uycOjdEdAAO93+vU2JBVP4Kh731uucpeN+2aBsJ4eGMiq+aGTQbRlJGbtEWt3CWpi1eMaRhVN3n9hfBW0Z8E9sDzE2+mX7yh+rHptJg8eeePvsp+iOrZK1/SZadNBRoSeM8c+4jCpJMDa3+D0ETOE8nFA8lGHK47gPKqALToffWuj2xPze+aZT3CKM625gD09ejRLZWyrotuD5pRXYHSZIdGClccu3Tmk4/7/Fau20Tupinf91RY/MzCyWC8Pjs31PFO5Yzse6Xylz5IQbrtTIfB/m9+jdSSjfN4ZbhtWmJ1tKwKWvUP1Pyu/5XGCY12aCPC+gJLko7Hc8BbYYID8Z+2QAE8yKEsHTh6uq8LTTA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
